<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='사막 빙글빙글 공사장'>사막 빙글빙글 공사장</option>"
putMap += "<option value='사막 놀라운 공룡 유적지'>사막 놀라운 공룡 유적지</option>"
putMap += "<option value='사막 오래된 송수관'>사막 오래된 송수관</option>"
putMap += "<option value='사막 베거이 시장'>사막 베거이 시장</option>"
putMap += "<option value='사막 버려진 오아시스'>사막 버려진 오아시스</option>"
putMap += "<option value='사막 지옥의 모래 구덩이'>사막 지옥의 모래 구덩이</option>"
putMap += "<option value='사막 피라미드 탐험'>사막 피라미드 탐험</option>"
putMap += "<option value='사막 스핑크스 수수께끼'>사막 스핑크스 수수께끼</option>"
putMap += "<option value='사막 울렁울렁'>사막 울렁울렁</option>"
putMap += "<option value='사막 더스트 2'>사막 더스트 2</option>"
putMap += "<option value='[리버스] 사막 빙글빙글 공사장'>[리버스] 사막 빙글빙글 공사장</option>"
putMap += "<option value='[리버스] 사막 베거이 시장'>[리버스] 사막 베거이 시장</option>"
putMap += "<option value='[리버스] 사막 버려진 오아시스'>[리버스] 사막 버려진 오아시스</option>"
putMap += "<option value='[리버스] 사막 지옥의 모래 구덩이'>[리버스] 사막 지옥의 모래 구덩이</option>"
putMap += "<option value='[리버스] 사막 피라미드 탐험'>[리버스] 사막 피라미드 탐험</option>"
putMap += "<option value='[리버스] 사막 울렁울렁'>[리버스] 사막 울렁울렁</option>"