<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='팩토리 미완성 5구역'>팩토리 미완성 5구역</option>"
putMap += "<option value='팩토리 부비트랩 공장 탐험'>팩토리 부비트랩 공장 탐험</option>"
putMap += "<option value='팩토리 두 개의 공장'>팩토리 두 개의 공장</option>"
putMap += "<option value='팩토리 우당탕 대소동'>팩토리 우당탕 대소동</option>"
putMap += "<option value='팩토리 브로디의 심술'>팩토리 브로디의 심술</option>"
putMap += "<option value='팩토리 모험의 시작'>팩토리 모험의 시작</option>"
putMap += "<option value='팩토리 거대톱니의 위협'>팩토리 거대톱니의 위협</option>"
putMap += "<option value='팩토리 부스터 제작의 비밀'>팩토리 부스터 제작의 비밀</option>"
putMap += "<option value='팩토리 수상한 증기 장치'>팩토리 수상한 증기 장치</option>"
putMap += "<option value='팩토리 핀저의 위험한 적재소'>팩토리 핀저의 위험한 적재소</option>"
putMap += "<option value='[리버스] 팩토리 브로디의 심술'>[리버스] 팩토리 브로디의 심술</option>"
putMap += "<option value='[리버스] 팩토리 모험의 시작'>[리버스] 팩토리 모험의 시작</option>"
putMap += "<option value='[리버스] 팩토리 거대톱니의 위협'>[리버스] 팩토리 거대톱니의 위협</option>"
putMap += "<option value='[리버스] 팩토리 우당탕 대소동'>[리버스] 팩토리 우당탕 대소동</option>"