<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='동화 이상한 나라의 문'>동화 이상한 나라의 문</option>"
putMap += "<option value='동화 잠자는 숲속의 거인'>동화 잠자는 숲속의 거인</option>"
putMap += "<option value='동화 다오와 콩나무'>동화 다오와 콩나무</option>"
putMap += "<option value='동화 프레티온 목마'>동화 프레티온 목마</option>"
putMap += "<option value='동화 목욕탕에 개굴개굴'>동화 목욕탕에 개굴개굴</option>"
putMap += "<option value='동화 카드왕국의 미로'>동화 카드왕국의 미로</option>"
putMap += "<option value='동화 가시덩굴괴물의 등장'>동화 가시덩굴괴물의 등장</option>"
putMap += "<option value='동화 마녀의 성'>동화 마녀의 성</option>"
putMap += "<option value='[리버스] 동화 프레티온 목마'>[리버스] 동화 프레티온 목마</option>"
putMap += "<option value='[리버스] 동화 목욕탕에 개굴개굴'>[리버스] 동화 목욕탕에 개굴개굴</option>"