<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='포레스트 지그재그'>포레스트 지그재그</option>"
putMap += "<option value='포레스트 아찔한 다운힐'>포레스트 아찔한 다운힐</option>"
putMap += "<option value='포레스트 오싹한 공중다리'>포레스트 오싹한 공중다리</option>"
putMap += "<option value='포레스트 대관령'>포레스트 대관령</option>"
putMap += "<option value='포레스트 통나무'>포레스트 통나무</option>"
putMap += "<option value='포레스트 골짜기'>포레스트 골짜기</option>"
putMap += "<option value='포레스트 버섯동굴'>포레스트 버섯동굴</option>"
putMap += "<option value='포레스트 기암괴석'>포레스트 기암괴석</option>"
putMap += "<option value='포레스트 폭포속으로'>포레스트 폭포속으로</option>"
putMap += "<option value='포레스트 행복한 팬더 마을'>포레스트 행복한 팬더 마을</option>"
putMap += "<option value='포레스트 유격장'>포레스트 유격장</option>"
putMap += "<option value='포레스트 바람의 봉래산'>포레스트 바람의 봉래산</option>"
putMap += "<option value='[리버스] 포레스트 지그재그'>[리버스] 포레스트 지그재그</option>"
putMap += "<option value='[리버스] 포레스트 통나무'>[리버스] 포레스트 통나무</option>"
putMap += "<option value='[리버스] 포레스트 골짜기'>[리버스] 포레스트 골짜기</option>"
putMap += "<option value='[리버스] 포레스트 버섯동굴'>[리버스] 포레스트 버섯동굴</option>"
putMap += "<option value='[리버스] 포레스트 기암괴석'>[리버스] 포레스트 기암괴석</option>"
putMap += "<option value='[리버스] 포레스트 행복한 팬더 마을'>[리버스] 포레스트 행복한 팬더 마을</option>"