<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='아이스 설산 다운힐'>아이스 설산 다운힐</option>"
putMap += "<option value='아이스 부서진 빙산'>아이스 부서진 빙산</option>"
putMap += "<option value='아이스 갈라진 빙산'>아이스 갈라진 빙산</option>"
putMap += "<option value='아이스 아찔한 헬기점프'>아이스 아찔한 헬기점프</option>"
putMap += "<option value='아이스 짜릿한 동계 훈련장'>아이스 짜릿한 동계 훈련장</option>"
putMap += "<option value='아이스 펭귄타운'>아이스 펭귄타운</option>"
putMap += "<option value='아이스 상어의 무덤'>아이스 상어의 무덤</option>"
putMap += "<option value='아이스 투명동굴'>아이스 투명동굴</option>"
putMap += "<option value='아이스 신나는 하프파이프'>아이스 신나는 하프파이프</option>"
putMap += "<option value='아이스 펭귄 전사 눈덩이 공격'>아이스 펭귄 전사 눈덩이 공격</option>"
putMap += "<option value='[리버스] 아이스 갈라진 빙산'>[리버스] 아이스 갈라진 빙산</option>"
putMap += "<option value='[리버스] 아이스 펭귄타운'>[리버스] 아이스 펭귄타운</option>"
putMap += "<option value='[리버스] 아이스 상어의 무덤'>[리버스] 아이스 상어의 무덤</option>"
putMap += "<option value='[리버스] 아이스 투명동굴'>[리버스] 아이스 투명동굴</option>"
putMap += "<option value='[리버스] 아이스 신나는 하프파이프'>[리버스] 아이스 신나는 하프파이프</option>"