<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='광산 꼬불꼬불 다운힐'>광산 꼬불꼬불 다운힐</option>"
putMap += "<option value='광산 아슬아슬 궤도 전차'>광산 아슬아슬 궤도 전차</option>"
putMap += "<option value='광산 위험한 제련소'>광산 위험한 제련소</option>"
putMap += "<option value='광산 3개의 지름길'>광산 3개의 지름길</option>"
putMap += "<option value='광산 보석채굴장'>광산 보석채굴장</option>"
putMap += "<option value='광산 뽀글뽀글 용암굴'>광산 뽀글뽀글 용암굴</option>"
putMap += "<option value='광산 떨어지는 폭포수'>광산 떨어지는 폭포수</option>"
putMap += "<option value='광산 롤러코스터 질주'>광산 롤러코스터 질주</option>"
putMap += "<option value='광산 무너지는 금광'>광산 무너지는 금광</option>"
putMap += "<option value='[리버스] 광산 보석채굴장'>[리버스] 광산 보석채굴장</option>"
putMap += "<option value='[리버스] 광산 뽀글뽀글 용암굴'>[리버스] 광산 뽀글뽀글 용암굴</option>"