<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='노르테유 익스프레스'>노르테유 익스프레스</option>"
putMap += "<option value='노르테유 우주 정거장'>노르테유 우주 정거장</option>"
putMap += "<option value='노르테유 코스모웨이'>노르테유 코스모웨이</option>"
putMap += "<option value='노르테유 위험한 지름길'>노르테유 위험한 지름길</option>"
putMap += "<option value='노르테유 허공의 갈림길'>노르테유 허공의 갈림길</option>"
putMap += "<option value='노르테유 우주선 침투'>노르테유 우주선 침투</option>"
putMap += "<option value='노르테유 붕붕 점프'>노르테유 붕붕 점프</option>"
putMap += "<option value='노르테유 부스터존 점령작전'>노르테유 부스터존 점령작전</option>"
putMap += "<option value='노르테유 행성 저 멀리'>노르테유 행성 저 멀리</option>"
putMap += "<option value='노르테유 전투비행장'>노르테유 전투비행장</option>"
putMap += "<option value='노르테유 숨막히는 터널 탈주'>노르테유 숨막히는 터널 탈주</option>"
putMap += "<option value='[리버스] 노르테유 코스모웨이'>[리버스] 노르테유 코스모웨이</option>"
putMap += "<option value='[리버스] 노르테유 위험한 지름길'>[리버스] 노르테유 위험한 지름길</option>"
putMap += "<option value='[리버스] 노르테유 허공의 갈림길'>[리버스] 노르테유 허공의 갈림길</option>"
putMap += "<option value='[리버스] 노르테유 우주선 침투'>[리버스] 노르테유 우주선 침투</option>"
putMap += "<option value='[리버스] 노르테유 붕붕 점프'>[리버스] 노르테유 붕붕 점프</option>"
putMap += "<option value='[리버스] 노르테유 부스터존 점령작전'>[리버스] 노르테유 부스터존 점령작전</option>"
putMap += "<option value='[리버스] 노르테유 우주 정거장'>[리버스] 노르테유 우주 정거장</option>"