<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='해적 가파른 감시탑'>해적 가파른 감시탑</option>"
putMap += "<option value='해적 로비 절벽의 전투'>해적 로비 절벽의 전투</option>"
putMap += "<option value='해적 숨겨진 보물'>해적 숨겨진 보물</option>"
putMap += "<option value='해적 상어섬의 비밀'>해적 상어섬의 비밀</option>"
putMap += "<option value='해적 위기일발 대탈출'>해적 위기일발 대탈출</option>"
putMap += "<option value='해적 짜릿한 고공비행'>해적 짜릿한 고공비행</option>"
putMap += "<option value='해적 어질어질 부둣가'>해적 어질어질 부둣가</option>"
putMap += "<option value='해적 폭풍속의 질주'>해적 폭풍속의 질주</option>"
putMap += "<option value='해적 해적선 보물탈취'>해적 해적선 보물탈취</option>"
putMap += "<option value='[리버스] 해적 로비 절벽의 전투'>[리버스] 해적 로비 절벽의 전투</option>"
putMap += "<option value='[리버스] 해적 위기일발 대탈출'>[리버스] 해적 위기일발 대탈출</option>"
putMap += "<option value='[리버스] 해적 짜릿한 고공비행'>[리버스] 해적 짜릿한 고공비행</option>"
putMap += "<option value='[리버스] 해적 폭풍속의 질주'>[리버스] 해적 폭풍속의 질주</option>"