<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
putMap += "<option value='빌리지 붐힐터널'>빌리지 붐힐터널</option>"
putMap += "<option value='빌리지 익스트림 경기장'>빌리지 익스트림 경기장</option>"
putMap += "<option value='빌리지 만리장성'>빌리지 만리장성</option>"
putMap += "<option value='빌리지 운명의 다리'>빌리지 운명의 다리</option>"
putMap += "<option value='빌리지 남산'>빌리지 남산</option>"
putMap += "<option value='빌리지 지우펀'>빌리지 지우펀</option>"
putMap += "<option value='빌리지 고가의 질주'>빌리지 고가의 질주</option>"
putMap += "<option value='빌리지 고가의 질주 2'>빌리지 고가의 질주 2</option>"
putMap += "<option value='빌리지 손가락'>빌리지 손가락</option>"
putMap += "<option value='빌리지 손가락 2'>빌리지 손가락 2</option>"
putMap += "<option value='빌리지 파괴된 손가락'>빌리지 파괴된 손가락</option>"
putMap += "<option value='빌리지 두개의 관문'>빌리지 두개의 관문</option>"
putMap += "<option value='빌리지 운하'>빌리지 운하</option>"
putMap += "<option value='빌리지 수로'>빌리지 수로</option>"
putMap += "<option value='빌리지 시계탑'>빌리지 시계탑</option>"
putMap += "<option value='빌리지 파괴된 시계탑'>빌리지 파괴된 시계탑</option>"
putMap += "<option value='빌리지 댐 위의 대결'>빌리지 댐 위의 대결</option>"
putMap += "<option value='[리버스] 빌리지 고가의 질주'>[리버스] 빌리지 고가의 질주</option>"
putMap += "<option value='[리버스] 빌리지 손가락'>[리버스] 빌리지 손가락</option>"
putMap += "<option value='[리버스] 빌리지 붐힐터널'>[리버스] 빌리지 붐힐터널</option>"
putMap += "<option value='[리버스] 빌리지 두개의 관문'>[리버스] 빌리지 두개의 관문</option>"
putMap += "<option value='[리버스] 빌리지 운하'>[리버스] 빌리지 운하</option>"
putMap += "<option value='[리버스] 빌리지 수로'>[리버스] 빌리지 수로</option>"
putMap += "<option value='[리버스] 빌리지 시계탑'>[리버스] 빌리지 시계탑</option>"